### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by benrap** [apsun/NoVpnMonitor#1]
Could you add a screenshot so I'll know what this module does? Thanks in advanve

**Comment by apsun** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14020276/13034557/2d94df14-d2fe-11e5-8603-0149b550a945.png)

**Comment by benrap** [comment]
Alright thanks. Will this work on cm13 (marshmallow)? And can you add another piece of code so it will also hide the key in the status bar?

**Comment by apsun** [comment]
It should work fine on CM. If you want to hide the VPN icon, you can try this: http://repo.xposed.info/module/de.defim.apk.notifyclean

**Comment by benrap** [comment]
Thanks!!!!!!!!!!!

**Comment by benrap** [comment]
The app you sent does not do this. Could you implement this in your app?

**Comment by apsun** [comment]
I took a look and it seems the icon is special - I have no idea how it's being created (it's not the same as the other icons, which is really weird). Maybe at a future time.

**Comment by benrap** [comment]
Thank you for checking it out
